### ISSUE TITLE
After upgrade to v1.0.0 css not showing

### ISSUE THREAD

**Issue by fenchu** [damianszczepanik/cucumber-reporting-jenkins#153] opened 2015-12-22 08:21 UTC
I upgraded jenkins to cucumber-reports  net.masterthought.jenkins:cucumber-reports:1.0.0
It looks like this:
![jenkins-cucumber-reports-poorcss](https://cloud.githubusercontent.com/assets/11349883/11950866/bde8c202-a88c-11e5-8869-6126c8429a6c.jpg)

Especially annoying with the steps that just lists monoline under each other.

Javascript and Flash is enabled.

Any idea what is wrong?. console reports no error.
Thanks for a great plugin.

**Comment by damianszczepanik** [comment] 2015-12-22 17:43
Duplicate of jenkinsci/cucumber-reports-plugin/issues/7

**Closed as completed by damianszczepanik** 2015-12-22 17:43 UTC
